configfile: '../config/config.yaml'

include: 'rules/snRNAseq_GE_magma.smk'
include: 'rules/snRNAseq_GE_scDRS.smk'
include: 'rules/snRNAseq_GE_LDSR.smk'

rule all:
    input:
        expand("../results/magma/snRNAseq_GE_{GWAS}.lvl_{LEVEL}.magma.gsa.out", GWAS = config['GWAS'], LEVEL = [1,2]),
        expand("../results/magma_conditional/magma_all_sig_and_skene_condition_{CONDITION}.gsa.out", CONDITION = config['MAGMA_CONDITIONS']),
        "../results/scDRS/SCZ.full_score.gz",
        "../results/scDRS/SCZ.scdrs_group.cluster_level_1",
        expand("../results/LDSR_part_herit/baseline_v1.2/snRNAseq_LDSR_{GWAS}_baseline.v1.2_summary.tsv", GWAS = config['GWAS'])
        
