# ------------  GWAS  ----------------
# Note that permissions for MDD & 23andMe GWAS required
GWAS:
    SCZ: https://figshare.com/ndownloader/files/28169757 
#    HEIGHT: https://portals.broadinstitute.org/collaboration/giant/images/6/63/Meta-analysis_Wood_et_al%2BUKBiobank_2018.txt.gz
#    ASD: https://figshare.com/ndownloader/files/28169292
#    ADHD: https://figshare.com/ndownloader/files/40036684
#    BPD: https://figshare.com/ndownloader/files/40036705    
#    MDD: /gluster/neurocluster/databank/c.mdnra_shared/summaryqc/restricted/wray-ripke-mattheisen-2017-mdd-23me/wray-ripke-mattheisen-2017-mdd-23me-summaryqc.tsv.gz    

# -----  OBJECT AND CLUSTER LEVEL -----
SEURAT_OBJ:
    shi_bc:
#    shi_bc_dwnSmpl:


# ------------  SLDSR  ----------------
CELL_TYPES:
    CGE:
    CGE_0:
    CGE_1:
    CGE_2:
    CGE_3:
    Early_InN:
    Early_InN_0:
    Early_InN_1:
    Early_InN_2:
    Early_InN_3:
    Early_InN_4:
    Early_InN_5:
    LGE:
    LGE_0:
    LGE_1:
    LGE_2:
    LGE_3:
    LGE_4:
    LGE_5:
    LGE_6:
    LGE_7:
    MGE:
    MGE_0:
    MGE_1:
    MGE_2:
    MGE_3:
    MGE_4:
    MGE_5:
    Microglia:
    Progenitor:
    Progenitor_0:
    Progenitor_1:
    Progenitor_2:
    Progenitor_3:
    Progenitor_4:
    Progenitor_5:
    Progenitor_6:
    Progenitor_7:
    Progenitor_8:
    Progenitor_9:
    Progenitor_10:

COND_CELL_A:
    CGE_1:
    CGE_2:
    LGE_1:
    LGE_2:
    LGE_4:
    MGE_2:
    MGE_3:

COND_CELL_B:
    CGE_1:
    CGE_2:
    LGE_1:
    LGE_2:
    LGE_4:
    MGE_2:
    MGE_3:

PUBLIC_CELL_TYPES:
    fetal_FC_ExN_2:
    fetal_FC_ExN_3:
    fetal_FC_ExN_4:
    fetal_GE_InN_2:
    fetal_Hipp_ExN_3:
    fetal_Hipp_ExN_5:
    mouse_InN:
    mouse_MSN:
    mouse_CA1:
    mouse_SS:
    adult_exCA1:
    adult_exCA3:
    adult_exPFC1:
    adult_exDG:
    adult_exPFC2:
    adult_GABA1:
    adult_GABA2:

DIFFEXP_CELL_TYPES:
    early_InN_vs_Prog:
    LGE_early_InN:
    MGE_early_InN:
    CGE_early_InN:

# ------------  MAGMA  -----------------
MAGMA_CONDITIONS:
    CGE_1:
    CGE_2:
    LGE_1:
    LGE_2:
    LGE_4:
    MGE_2:
    MGE_3:


GENE_WINDOW:
#    0UP_0DOWN:
#    10UP_10DOWN:
#    35UP_10DOWN:
    100UP_100DOWN:

# Level only required for MAGMA
LEVEL:
    1:
    2:



