# ------------  GWAS  ----------------
GWAS:
    SCZ:
    HEIGHT:

# -----  OBJECT AND CLUSTER LEVEL -----
SEURAT_OBJ:
    shi_bc:
#    shi_bc_dwnSmpl:


# ------------  SLDSR  ----------------
CELL_TYPES:
    CGE:
    CGE_0:
    CGE_1:
    CGE_2:
    CGE_3:
    Early_InN:
    Early_InN_0:
    Early_InN_1:
    Early_InN_2:
    Early_InN_3:
    Early_InN_4:
    Early_InN_5:
    LGE:
    LGE_0:
    LGE_1:
    LGE_2:
    LGE_3:
    LGE_4:
    LGE_5:
    LGE_6:
    LGE_7:
    MGE:
    MGE_0:
    MGE_1:
    MGE_2:
    MGE_3:
    MGE_4:
    MGE_5:
    Microglia:
    Progenitor_0:
    Progenitor_1:
    Progenitor_2:
    Progenitor_3:
    Progenitor_4:
    Progenitor_5:
    Progenitor_6:
    Progenitor_7:
    Progenitor_8:
    Progenitor_9:
    Progenitor_10:

COND_CELL_A:
    CGE_1:
    CGE_2:
    LGE_1:
    LGE_2:
    LGE_4:
    MGE_2:
    MGE_3:

COND_CELL_B:
    CGE_1:
    CGE_2:
    LGE_1:
    LGE_2:
    LGE_4:
    MGE_2:
    MGE_3:

ADULT_CELL_TYPES:
    skene_InN:
    skene_MSN:

# ------------  MAGMA  -----------------
MAGMA_CONDITIONS:
    skene_InN:
    skene_MSN:
    CGE_1:
    CGE_2:
    LGE_1:
    LGE_2:
    LGE_4:
    MGE_2:
    MGE_3:


GENE_WINDOW:
    0UP_0DOWN:
    10UP_10DOWN:
    35UP_10DOWN:
    100UP_100DOWN:

# Level only required for MAGMA
LEVEL:
    1:
    2:

# ------------  scDRS  -----------------
H5AD_OBJ:
    shi_bc:
    shi_bc_LGE:
    shi_bc_MGE:
    shi_bc_CGE:
    shi_bc_Progenitor:

H5AD_OBJ_SUBCLUST:
    shi_bc_LGE:
    shi_bc_MGE:
    shi_bc_CGE:
    shi_bc_Progenitor:



